### ISSUE TITLE
cuda accelerate 

### ISSUE THREAD

**Issue by JsBlueCat** [Chia-Network/chiapos#188]
this is a mamagical code!
can the plotter be accelerated by cuda or rocm or opencl?

**Comment by Jieli1994-miner** [comment]
In my mined, many operation may be move to gpu，like sorting.  But the authors may not support cuda acceleration, which will consume a lot of power.

**Comment by hoffmang9** [comment]
If you can speed plotting up with GPU we are excited about it. However the memory requirements around total throughput and size may be challenging in making a GPU implementation performant.

**Comment by room101-dev** [comment]
Cuda has lots of restrictions in programming, say you have an 8gb gtx-1070, you can only allocate say 750mb at a time, lots of buffers  in this code are very large. While linux shared memory automatically support 4gb memory blocks.

Another approach, if you really want to enable cuda ( nvidia-gpu ), is to convert the plot-create to python, and then use the python-cuda library routine to automatically use cuda, but normally more is lost transferring to cuda memory than is gained by cuda

Traditional mining like sha256 is a small algo, where 1,000's of cores can all at the same time be working on separate solutions. While this software seems to be moving large blocks around, not really the right task for a cuda-gpu.

open-cl doesn't seem to be used much anymore. If your serious, look at the pycuda library, as much of CHIA is written in python. Even  the plotter_disk.hpp (C++) source here to generate plots, there are tools to generate cuda code. However I think for just playing around testing, it would be better to convert to python, and play with smaller -Kn plots.

The area of speed up, is the transfer delay, as most of the computation is the first hour of plotting, real gains would be plotting with 256GB RAM (DDR5-6), and using super high-end cpus with many TB of shared memory. I can see the Chinese working on such a machine, could be produced.

**Comment by Chewbakka-Wakka** [comment]
I have two boxes, one with 128GB and 256GB RAM. Would be good to know what options to pass to plot in the most efficient way.

**Comment by hocheung20** [comment]
I have moderately high memory machine (384GB) but even with a linux tmpfs ramdisk, there is no improvement over a fast SSD (personally tested with a 970 Pro 1TB and 905p 960GB).

The entire code appears to be written in such a way so that everything is a synchronous stream disk reads and write which I believe to be the major bottleneck to increasing performance.

**Comment by Chewbakka-Wakka** [comment]
I would try zfs and on your pool set sync=disabled on the initial plotting (temporarily) to verify this. All write calls made sync to disk will be acknowledged by this thread immediately which can only speed up the process.

**Comment by hocheung20** [comment]
tmpfs is not zfs. There are no sync options for tmpfs because literally tmpfs is RAM-backed and there is no underlying device to "sync" to.

**Comment by hocheung20** [comment]
Just to clarify confusion a little bit, when I say "synchronous", I don't mean the synchronicity of the underlying device. 

I actually mean the synchronicity between performing I/O and computation. Because the model is a single-thread synchronous computation, whenever the CPU is performing I/O, it is not doing compute and also vice versa.

In the age of spinning rust, the I/O is often so slow that we aren't really gaining that much by overlapping computation and I/O, but in the age of SSDs, they are so fast the overhead of performing I/O (calling disk-based interfaces like seek and copying things around in buffers) actually dominates the work to be done and doesn't have much benefits.

Additionally, most NAND-based SSDs perform much better when put under pressure (i.e. higher queue depths) which you can't achieve with a single-threaded synchronous disk interface.

**Comment by JsBlueCat** [comment]
https://github.com/madMAx43v3r/chia-plotter.git
now, there is a pipelined realization for cpu. 
until now,i also think there should be a cuda realization for this.  i think there can be two thread pools. one for launch_kernal, one for launch_cpu. and with ram tmpfs as a global memory. one thing that break is that cpu memory need to sync. with  gpu L2,L1 memory. with cuda high throughput low latancy it can be more faster.

**Comment by emlowe** [comment]
closing issue - community enhancements to plotting will be considered for merging, but it's unlikely we will initiate GPU work in this area
