### ISSUE TITLE
Chia plotting stops/hangs up at some point with CPU thread at 100%

### ISSUE THREAD

**Issue by tinodj** [Chia-Network/chiapos#234]
Hi, 

this could be hw related, but however, maybe software can/should get out of the loop and print some error message, so one can easier investigate what the problem is. And also, stop waisting resources, rather terminate if can't make any progress. 

At our side it stops at random places, in the 3rd phase mostly. I have all the data ( p3.t2.sort_bucket_xxx.tmp ) saved at the point it stopped, if you want me to enable some logging/debugging from here on. Last message I had was about sorting bucket 53, in table 1/2 in phase 3. 

I took a look into the code very briefly, and I can see several while-s going on here, so some of them might not be terminating properly. Please note - no disk activity is happening, while the processor thread is running at 100%. 

If you suspect hardware, what it would be? RAM / DISK or something else? 

If you give me some instructions how to run more verbose/debugging version, I can do that and maybe that will nail down this problem for me and for others. 

This seems related:
https://github.com/Chia-Network/chia-blockchain/discussions/3228#discussioncomment-687990

**Comment by tinodj** [comment]
Great @mhurliman that you will do some debugging. Please share if you find something. I will have no time before weekend to do any debugging on this, unfortunately. We have one plotter running without any troubles but we got these troubles on the second one (similar config to the first one). For now we suspect faulty RAM.

**Comment by arvidn** [comment]
when plotting behaves strange, it's a good idea to run [memtest](https://www.memtest86.com/).

**Comment by mhurliman** [comment]
Thanks for the response arvidn - I'll get it a run!

**Comment by room101-dev** [comment]
**> when plotting behaves strange, it's a good idea to run [memtest](https://www.memtest86.com/).**

That's the common retort here, but what I find is even better, is try another NVME I run 3 on my plotter, seeing the same problems, and read this site and all the comments were RAM, and I did run memtest++ at boot, just for the hell, but in deeper analysis I found it was only one NVME having the problem, and looking into 'sudo nvme smart-log /dev/xxx' I found some troubling stat's, seems that around 25% of warrany TBW this stuff starts happening, I know on this particular NVME that sky-rocketing temp +90C was the first thing, followed by hangs, and then what didn't hang blew out at post with 'mis-match' on plot completion, which means you lose that plot.

Seems to be some kind of un-stability as NVME's are stressed +2 weeks, certainly running 'fstrim' can help on early early hangs, watch the temp once the NVME becomes terminal it can no longer be used for -t ( temp dir ) plotting, but most interesting is they can be used with -2 (temp dir2), I suspect this is because the large-contiguous file in the controller has not been broken, but the random access has been hosed.

Now that I have the source for plot-create-disk in C++, I'll setup debugging tools to catch the problem using known defective NVME's. Its interesting, that while these NVME's are ok, for normal usage they fail with chia-plotting. There is a point where even fstrim no longer helps the slow-down in plotting.

Running an aorus with two onboard NVME's and a pcie on the 4x slot nearest cpu, its seems that most of the time its the m.2 nearest the cpu that goes out first, I also have fans on all the NVME's now just for a precaution. One bad thing about water-cooling on the AMD 32core cpu is that there's no air blowing around the M.2 slots. ( now there is )

64GB RAM has always been fine, never a problem this is a new system

I have also quit running 'chia start' blockchain stuff on the plotting machine, now its 100% 'chia create plot', and nothing else running, even 'plotman' which is supposed to be 'passive' I found was adding additional plots to the 'free space', for me the sweet spot is 4 plots per NVME, and plotman tried to add 12 argggggggggh :(

But yes, lots of debugging is needed to find these cpu endless loops, and narrow down the code, I'll use 'valgrind' which is the best for this kind of work, but honestly this is late symptom of the NVME failure, more important is find out why the NVME is getting destroyed, it might be as simple as the endless loop condition is what is destroying drives????

The other thing I have done is a fall back to '13' version of chia-net/blockchain as most of these problems weren't so common as  now, I think some of this may be the result of making the plotter code 'faster'.

**Comment by arvidn** [comment]
if you make sure to have debug info in the chiapos build, it should be pretty straigh-forward to attach gdb to the python process and see what's going on.

**Comment by vnagara** [comment]
Hi I have the same issue on 1 of my computers. Plotting went in endless loop on 3 different disks 5 out 5 times. Stops around compressing table 3-5. No error displayed/logged :((

**Comment by tinodj** [comment]
@room101-dev @mhurliman any news from your debugging? 

I had no time to do debugging, but looking into the code/logs and behaviour - my eyes are somehow on the following lines:

https://github.com/Chia-Network/chiapos/blob/b014e05f6dee1092fe42c76afe10a239abf440a3/src/uniformsort.hpp#L74-L84

But, also somewhere in the quicksort (maybe in the recursion): https://github.com/Chia-Network/chiapos/blob/b014e05f6dee1092fe42c76afe10a239abf440a3/src/quicksort.hpp
