### ISSUE TITLE
Problem with double process buckets... 

### ISSUE THREAD

**Issue by CoderArgentina** [Chia-Network/chiapos#247]
I am having problem with the phase 3, it process every bucket 2 times with half ram... when the pc has 50% free ram.

	Bucket 29 uniform sort. Ram: 1.906GiB, u_sort min: 1.250GiB, qs min: 0.328GiB.
	Bucket 29 uniform sort. Ram: 1.906GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 30 uniform sort. Ram: 1.906GiB, u_sort min: 1.250GiB, qs min: 0.329GiB.
	Bucket 30 uniform sort. Ram: 1.906GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 31 uniform sort. Ram: 1.906GiB, u_sort min: 1.250GiB, qs min: 0.329GiB.
	Bucket 31 uniform sort. Ram: 1.906GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.
	Bucket 32 uniform sort. Ram: 1.906GiB, u_sort min: 1.250GiB, qs min: 0.329GiB.
	Bucket 32 uniform sort. Ram: 1.906GiB, u_sort min: 0.500GiB, qs min: 0.250GiB.

I have 32gb, and currently have 5 process with 4000 MB each.

The process monitor reports 44% of ram in use... what can i do? im testing but i think that the plot time is going up..

**Comment by gegorov2030** [comment]
I think I have the same problem
```
Compressing tables 5 and 6
	Bucket 0 uniform sort. Ram: 7.776GiB, u_sort min: 2.500GiB, qs min: 0.657GiB.
	Bucket 0 uniform sort. Ram: 7.776GiB, u_sort min: 1.000GiB, qs min: 0.500GiB.
	Bucket 1 uniform sort. Ram: 7.776GiB, u_sort min: 2.500GiB, qs min: 0.657GiB.
	Bucket 1 uniform sort. Ram: 7.776GiB, u_sort min: 1.000GiB, qs min: 0.500GiB.
	Bucket 2 uniform sort. Ram: 7.776GiB, u_sort min: 2.500GiB, qs min: 0.657GiB.
	Bucket 2 uniform sort. Ram: 7.776GiB, u_sort min: 1.000GiB, qs min: 0.500GiB.
	Bucket 3 uniform sort. Ram: 7.776GiB, u_sort min: 2.500GiB, qs min: 0.657GiB.
	Bucket 3 uniform sort. Ram: 7.776GiB, u_sort min: 1.000GiB, qs min: 0.500GiB.
...
	Bucket 52 QS. Ram: 7.776GiB, u_sort min: 1.250GiB, qs min: 0.430GiB. force_qs: 1
	Bucket 52 QS. Ram: 7.776GiB, u_sort min: 1.000GiB, qs min: 0.327GiB. force_qs: 1
	First computation pass time: 2701.849 seconds. CPU (82.580%) Wed May 19 13:36:39 202
```

**Comment by gegorov2030** [comment]
@grabypoker yes, 16 parallel tasks with
-k 32 -r 6 -u 64 -b 16000

**Comment by grabypoker** [comment]
256gb ram?

**Comment by gegorov2030** [comment]
<img width="1317" alt="Screen Shot 2021-05-19 at 3 50 26 PM" src="https://user-images.githubusercontent.com/59376336/118894876-f099bd80-b8b9-11eb-845c-c822954c9849.png">
The memory is allocated with reserve, 128GB is enough

**Comment by CoderArgentina** [comment]
I dont understand 100%.. but in ny case i can sum all 4000mb and got 24gb ram... so 8 are free.. dont know why this happens

**Comment by arvidn** [comment]
those are buckets in different tables. As the title suggests, `Compressing tables 5 and 6`, both of those tables, at that point, are still split up into unsorted buckets. When we do a processing pass over both of those tables, we read and sort the first bucket from each tablem process them linearly, and then move on to the next bucket in both tables. (the buckets may have slightly different sizes and both tables may not switch to the next bucket in lock-step).

The reason we use half the RAM for those buckets is because we do two of them at the same time. This is to not exceed the memory budget given to the plotter. If you want to give it more RAM, there's a switch for that.

**Comment by emlowe** [comment]
Closing issue
